apiversion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vinayakchamle/argocd-global-training.git
    targetRevision: HEAD
    path: training
 destination:
   server: https://kubernetes.default.svc
   namespace: argocd

syncPolicy:
  SyncOptions:
  - CreateNamespace=true
 
  automated:
    selfHeal: true
    prune: true