apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui-redis
  namespace: argocd
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui-redis
  template:
    metadata:
      labels:
        app: guestbook-ui-redis
    spec:
      containers:
      - image: vinayakchamle/redis-image:latest
        name: guestbook-ui-redis
        ports:
        - containerPort: 81