apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-redis
  namespace: argocd
spec:
  selector:
    matchLabels:
      app: myapp-redis
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp-redis
    spec:
      containers:
      - name: myapp-redis
        image: vinayakchamle/redis-image:latest
        ports:
        - containerPort: 6379
